services:
  splunk-cluster-master:
    image: splunk/splunk:latest
    container_name: splunk-cluster-master
    hostname: cluster-master
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8089:8089"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=SplunkAdmin123!
    volumes:
      - splunk-data:/opt/splunk/var
    networks:
      - splunk-net

networks:
  splunk-net:

volumes:
  splunk-data:
