services:
  # Generic Indexer service (for deployment validation)
  indexer:
    image: "${SPLUNK_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-splunk}_indexer"
    hostname: "indexer"
    restart: unless-stopped
    ports:
      - "8000:8000"  # Splunk Web
      - "8089:8089"  # Management port
      - "9997:9997"  # Splunk2Splunk
      - "8088:8088"  # HTTP Event Collector
    environment:
      SPLUNK_START_ARGS: "--accept-license --answer-yes"
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_ROLE: "splunk_standalone"
      SPLUNK_PASSWORD: "${SPLUNK_PASSWORD}"
      SPLUNK_SECRET: "${SPLUNK_SECRET}"
    networks:
      - splunk-net
    volumes:
      - indexer-etc:/opt/splunk/etc
      - indexer-var:/opt/splunk/var
    profiles: ["small", "splunk"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/splunk/bin/splunk status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

networks:
  splunk-net:
    name: "${COMPOSE_PROJECT_NAME:-splunk}_cluster_network"
    driver: bridge

volumes:
  indexer-etc:
    name: "${COMPOSE_PROJECT_NAME:-splunk}_indexer_etc"
  indexer-var:
    name: "${COMPOSE_PROJECT_NAME:-splunk}_indexer_var"
