version: '3.8'

services:
  indexer1:
    image: splunk/splunk:latest
    container_name: splunk-indexer1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=Splunk123!
      - SPLUNK_ROLE=indexer
    ports:
      - "9997:9997"
    volumes:
      - splunk-indexer1-data:/opt/splunk/var
      - splunk-indexer1-etc:/opt/splunk/etc
    networks:
      - splunk-network

  indexer2:
    image: splunk/splunk:latest
    container_name: splunk-indexer2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=Splunk123!
      - SPLUNK_ROLE=indexer
    ports:
      - "9998:9997"
    volumes:
      - splunk-indexer2-data:/opt/splunk/var
      - splunk-indexer2-etc:/opt/splunk/etc
    networks:
      - splunk-network

  search-head:
    image: splunk/splunk:latest
    container_name: splunk-search-head
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=Splunk123!
      - SPLUNK_ROLE=search_head
    ports:
      - "8000:8000"
    volumes:
      - splunk-search-head-data:/opt/splunk/var
      - splunk-search-head-etc:/opt/splunk/etc
    networks:
      - splunk-network

volumes:
  splunk-indexer1-data:
  splunk-indexer1-etc:
  splunk-indexer2-data:
  splunk-indexer2-etc:
  splunk-search-head-data:
  splunk-search-head-etc:

networks:
  splunk-network:
    driver: bridge
